version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3308:3306'
    volumes:
      - C:\Users\dns\IdeaProjects\SQL\src\init:/docker-entrypoint-initdb.d/:ro
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass